### ISSUE TITLE
This repository is outdated

### ISSUE THREAD

**Issue by pdonorio** [dockerfile/rethinkdb#7]
I tried building my own image for getting the latest Rethinkdb 2.1.4.

There is no "dockerfile/ubuntu" anymore:

```
$ docker pull dockerfile/ubuntu                           
Using default tag: latest
Pulling repository docker.io/dockerfile/ubuntu
Error: image dockerfile/ubuntu:latest not found
```

It's just "ubuntu" and comes with no `wget` installed.
So you should also add

```
RUN apt-get update && apt-get install -y wget
```

Does the automatic build still works?
Thanks for your great work and your great database.

Paolo

**Comment by joshbedo** [comment]
+1 Seeing the same issue

**Comment by pdonorio** [comment]
Maybe it can help someone, i solved wroting my latest rethinkdb taking the example from this repo.

Here is the public link:
https://hub.docker.com/r/pdonorio/myrethinkdb/

And this is the Dockerfile i used:
https://github.com/pdonorio/dockerizing/blob/master/databases/rethinkdb/Dockerfile

**Comment by pdonorio** [comment]
Bump.

No time Docker anymore?
Would gladly help, if possible.

**Comment by elifarley** [comment]
See https://github.com/rethinkdb/rethinkdb-dockerfiles

**Comment by pdonorio** [comment]
Ok, thanks!
